version: '3.1'
services:
  ewm-stats:
    build:
      context: ./ewm-stats/stats-server
      dockerfile: Dockerfile
    image: stats-server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats-db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: stats-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  ewm-main:
    build:
      context: ./ewm-main
      dockerfile: Dockerfile
    image: ewm-main
    container_name: ewm-main-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - ewm-stats
    environment:
      STATS_SERVER_URL: http://ewm-stats:9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm-db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: ewm-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
